# Invalid CertsuiteRun for testing purposes.
# Invalidation reason: unsupported loglevel.
apiVersion: best-practices-for-k8s.openshift.io/v1alpha1
kind: CertsuiteRun
metadata:
  labels:
    app.kubernetes.io/name: certsuiterun
    app.kubernetes.io/instance: certsuiterun-invalid-sample
    app.kubernetes.io/part-of: certsuite-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: certsuite-operator
  name: certsuiterun-sample10
  namespace: certsuite-operator
spec:
  # TODO(user): Add fields here
  labelsFilter: "observability"
  logLevel: "unsupported-log-level"
  timeout: "2h"

  configMapName: "certsuite-config"
  preflightSecretName : "certsuite-preflight-dockerconfig"