# permissions for end users to view cnfcertificationsuiteruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cnfcertificationsuiterun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cnf-certsuite-operator
    app.kubernetes.io/part-of: cnf-certsuite-operator
    app.kubernetes.io/managed-by: kustomize
  name: cnfcertificationsuiterun-viewer-role
rules:
- apiGroups:
  - cnf-certifications.openshift.io
  resources:
  - cnfcertificationsuiteruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cnf-certifications.openshift.io
  resources:
  - cnfcertificationsuiteruns/status
  verbs:
  - get
