apiVersion: cnf-certifications.redhat.com/v1alpha1
kind: CnfCertificationSuiteRun
metadata:
  labels:
    app.kubernetes.io/name: cnfcertificationsuiterun
    app.kubernetes.io/instance: cnfcertificationsuiterun-sample
    app.kubernetes.io/part-of: tnf-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tnf-op
  name: cnfcertificationsuiterun-sample
spec:
  # TODO(user): Add fields here
