apiVersion: cnf-certifications.redhat.com/v1alpha1
kind: CnfCertificationSuiteReport
metadata:
  labels:
    app.kubernetes.io/name: cnfcertificationsuitereport
    app.kubernetes.io/instance: cnfcertificationsuitereport-sample
    app.kubernetes.io/part-of: tnf-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tnf-op
  name: cnfcertificationsuitereport-sample
spec:
  # TODO(user): Add fields here
